apiVersion: v2
name: kalypso-otel
description: OpenTelemetry Operator for Kalypso infrastructure (requires cert-manager)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: opentelemetry-operator
    version: "0.102.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-operator.enabled
  - name: opentelemetry-ebpf-instrumentation
    version: "0.4.3"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-ebpf-instrumentation.enabled
