{{- if .Values.otelCollector.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kalypso-otel.fullname" . }}-collector
  labels:
    {{- include "kalypso-otel.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kalypso-otel.fullname" . }}-collector
  labels:
    {{- include "kalypso-otel.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
rules:
  # k8sattributes processor
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "watch", "list"]
  # k8s_observer extension
  - apiGroups: [""]
    resources: ["endpoints", "services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kalypso-otel.fullname" . }}-collector
  labels:
    {{- include "kalypso-otel.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kalypso-otel.fullname" . }}-collector
subjects:
  - kind: ServiceAccount
    name: {{ include "kalypso-otel.fullname" . }}-collector
    namespace: {{ .Release.Namespace }}
{{- end }}
