{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kalypso-otel.fullname" . }}-collector
  labels:
    {{- include "kalypso-otel.labels" . | nindent 4 }}
{{- end }}
