kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
  # Control plane node
  - role: control-plane

  # Worker node 1
  - role: worker
  - role: worker

# Networking configuration
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
