apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.28.3
    releaseName: istio-base
    namespace: istio-system
    valuesFile: values-base.yaml

  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.28.3
    releaseName: istiod
    namespace: istio-system
    valuesFile: values-istiod.yaml

resources:
  - namespace.yaml
