apiVersion: v2
name: kalypso-mimir
description: Grafana Mimir metrics storage for Kalypso infrastructure
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mimir-distributed
    version: "6.1.0-weekly.373"
    repository: "https://grafana.github.io/helm-charts"
    condition: mimir-distributed.enabled
