apiVersion: v2
appVersion: v0.4.1
description: OpenTelemetry eBPF instrumentation Helm chart for Kubernetes
home: https://opentelemetry.io/
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
maintainers:
- name: dmitryax
- name: jaronoff97
- name: TylerHelmuth
- name: nimrodavni78
name: opentelemetry-ebpf-instrumentation
sources:
- https://github.com/coralogix/opentelemetry-helm-charts
- https://github.com/open-telemetry/opentelemetry-helm-charts
type: application
version: 0.4.3
