apiVersion: v1
kind: ServiceAccount
metadata:
  name: kalypso-otel-collector
  namespace: otel-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kalypso-otel-collector
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kalypso-otel-collector
subjects:
  - kind: ServiceAccount
    name: kalypso-otel-collector
    namespace: otel-system
roleRef:
  kind: ClusterRole
  name: kalypso-otel-collector
  apiGroup: rbac.authorization.k8s.io
