apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kalypso-infra
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: cert-manager
            namespace: cert-manager
            path: manifests/cert-manager
            wave: "0"
          - name: otel
            namespace: otel-system
            path: manifests/otel
            wave: "1"
          - name: istio
            namespace: istio-system
            path: manifests/istio
            wave: "2"
          - name: minio
            namespace: minio
            path: manifests/minio
            wave: "3"
          - name: mimir
            namespace: mimir
            path: manifests/mimir
            wave: "4"
          - name: tempo
            namespace: tempo
            path: manifests/tempo
            wave: "4"
          - name: loki
            namespace: loki
            path: manifests/loki
            wave: "4"
          - name: pyroscope
            namespace: pyroscope
            path: manifests/pyroscope
            wave: "5"
          - name: grafana
            namespace: grafana
            path: manifests/grafana
            wave: "6"
  
  template:
    metadata:
      name: 'kalypso-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: kalypso-infra
      
      source:
        repoURL: https://github.com/KalypsoServing/helm-charts.git
        targetRevision: HEAD
        path: '{{path}}'
        kustomize:
          enableHelm: true
      
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
