apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kalypso-infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/KalypsoServing/helm-charts.git
        revision: HEAD
        files:
          - path: manifests/*/namespace.yaml
  template:
    metadata:
      name: 'kalypso-{{.path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{index .metadata.annotations "argocd.argoproj.io/sync-wave"}}'
    spec:
      project: kalypso-infra
      
      source:
        repoURL: https://github.com/KalypsoServing/helm-charts.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        kustomize:
          enableHelm: true
      
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.metadata.name}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
