fullnameOverride: kalypso-minio

minio:
  enabled: true
  mode: standalone
  replicas: 1
  drivesPerNode: 1
  
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
  
  rootUser: "rootuser"
  rootPassword: "rootpass123"
  
  persistence:
    enabled: true
    size: 10Gi
  
  buckets:
    - name: tempo-bucket
      policy:
      purge: false
    - name: loki-bucket
      policy:
      purge: false
    - name: mimir-bucket
      policy:
      purge: false
    - name: mimir-blocks
      policy:
      purge: false
    - name: mimir-alertmanager
      policy:
      purge: false
    - name: mimir-ruler
      policy:
      purge: false
    - name: pyroscope-data
      policy:
      purge: false
    - name: pyroscope-admin
      policy:
      purge: false
  
  service:
    type: LoadBalancer
    port: 9000
  
  consoleService:
    type: LoadBalancer
    port: 9001

# Global configuration for credentials
global:
  minio:
    rootUser: "rootuser"
    rootPassword: "rootpass123"
