apiVersion: v2
name: kalypso-loki
description: Grafana Loki log aggregation
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: loki
    version: "6.49.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
