apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

helmCharts:
  - name: minio
    repo: https://charts.min.io/
    version: 5.4.0
    releaseName: kalypso-minio
    namespace: minio
    valuesFile: values.yaml

resources:
  - namespace.yaml
