mode: standalone
replicas: 1
drivesPerNode: 1
resources:
  requests:
    memory: 256Mi
    cpu: 100m
rootUser: "rootuser"
rootPassword: "rootpass123"
persistence:
  enabled: true
  size: 10Gi
buckets:
  - name: tempo-bucket
    policy: none
    purge: false
  - name: loki-bucket
    policy: none
    purge: false
  - name: mimir-bucket
    policy: none
    purge: false
  - name: mimir-blocks
    policy: none
    purge: false
  - name: mimir-alertmanager
    policy: none
    purge: false
  - name: mimir-ruler
    policy: none
    purge: false
  - name: pyroscope-data
    policy: none
    purge: false
  - name: pyroscope-admin
    policy: none
    purge: false
service:
  type: ClusterIP
  port: 9000
consoleService:
  type: ClusterIP
  port: 9001
