# Istio base configuration
base:
  enabled: true

# Istio control plane (istiod) configuration
istiod:
  enabled: true
  pilot:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
